article/urls.py
from django.urls import path
from . import views

app_name = 'article'
urlpatterns = [
    # path('about', views.about_view, name='about'),
    # path('', list_view, name='article-list'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='article-detail'),
    path('create/', views.ArticleCreateView.as_view(), name='article-create'),
    path('<int:pk>/update/', views.ArticleUpdateView.as_view(), name='article-update'),
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article-delete'),
    path('<int:pk>/like', views.IncreaseLikesView.as_view(), name='article-like'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from article.views import ArticleListView
from blog import settings
from django.conf.urls.static import static

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # apps
    path('article/', include('article.urls')),
    path('user/', include('userprofile.urls')),
    path('comment/', include('comment.urls')),
    path('mdeditor/', include('mdeditor.urls')),

    # main site
    path('', ArticleListView.as_view(), name='article-list'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from . import views
from django.urls import path

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete')
    ]

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-4.1.3/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.staticfile.org/hover.css/2.3.1/css/hover-min.css"
          onerror="this.insertAdjacentHTML('afterEnd', '<link rel=&quot;stylesheet&quot; href={% static 'hover/hover-min.css' %} >')">
    {#<link rel="stylesheet" href="{% static 'hover/hover-min.css' %}">#}
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          crossorigin="anonymous"
    >
    <style type="text/css">
        .modal-open {
            overflow: auto;
            padding-right: 0 !important;
        }
    </style>
    {% block style %}{% endblock style %}
</head>
<body>
    {% include 'nav.html' %}

    {% block content %}{% endblock content %}

    {% include 'footer.html' %}

    {# include js files #}
    <script type="text/javascript" src="https://cdn.staticfile.org/jquery/3.4.1/jquery.min.js"
            onerror="this.insertAdjacentHTML('afterEnd', '<script src={% static 'jquery-3.4.1/jquery.min.js' %} ></script>')"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js"
            onerror="this.insertAdjacentHTML('afterEnd', '<script src={% static 'bootstrap-4.1.3/js/bootstrap.min.js' %} ></script>')"
    ></script>
    <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"
            onerror="this.insertAdjacentHTML('afterEnd', '<script src={% static 'bootstrap-4.1.3/js/bootstrap.bundle.min.js' %} ></script>')"></script>
    <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/bootstrap-dropdown-hover@4.2.0/dist/jquery.bootstrap-dropdown-hover.min.js"
            onerror="this.insertAdjacentHTML('afterEnd', '<script src={% static 'bootstrap-dropdown-hover/jquery.bootstrap-dropdown-hover.min.js' %} ></script>')
                    "></script>
    <script type="text/javascript" src="{% static 'layer/layer.js' %}"></script>
    <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/sticky-sidebar@3.3.1/dist/jquery.sticky-sidebar.min.js"
            onerror="this.insertAdjacentHTML('afterEnd', '<script src={% static 'sticky-sidebar/jquery.sticky-sidebar.min.js' %} ></script>')"></script>
  
    {% include 'script.html' %}
    {% block script %}{% endblock script %}
</body>
</html>

templates/footer.html
{% load static %}

<div>
    <br><br><br>
</div>

<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; windyh.me 2020</p>
    </div>
</footer>

templates/nav.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a href="{% url 'article-list' %}" class="navbar-brand hvr-rotate">Windy's Blog</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'article-list' %}" class="nav-link">Blog List</a>
                </li>

                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="outline: none">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a href="{% url 'article:article-create' %}" class="dropdown-item text-dark">Write New Blog</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item text-warning" href="{% url 'userprofile:logout' %}">Log out</a>
                            <div class="dropdown-divider"></div>
                            {#<a class="dropdown-item text-danger" href="#" onclick="user_delete()">Delete account</a>#}
                            <a class="dropdown-item text-danger" href="#" data-toggle="modal"
                               data-target="#confirm-user-delete">Delete account</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">Log in</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

templates/script.html
{% if user.is_authenticated %}
    <form
            style="display:none;"
            id="user_delete"
            action="{% url 'userprofile:delete' user.pk %}"
            method="POST"
    >
        {% csrf_token %}
        <button type="submit">Submit</button>
    </form>

    <div class="modal fade" id="confirm-user-delete" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm delete</h5>
                    <button class="close" data-dismiss="modal" style="outline: none">&times;</button>
                </div>
                <div class="modal-body">
                    <p>confirm to delete the account?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-danger" onclick="user_delete()">DELETE</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<script>
    {# navbar hover dropdown #}
    $('.navbar [data-toggle="dropdown"]').bootstrapDropdownHover(
        {
            'clickBehavior': 'disable',
            'hideTimeout': 100,
        });
    /*
    $("#user_delete_btn").click(function () {
        console.log($("form#safe_delete"))
        {#$("form#safe_delete").click();#}
    });
    */

    function user_delete() {
        {#console.log($('form#safe_delete').innerHTML);#}
        $('form#user_delete button').click();
    }

</script>